[package]
name = "gpu_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvml-wrapper = "0.8.0"
once_cell = "1.13.1"
pretty-bytes ="0.2.2"
sysinfo = "0.25.2"
