[package]
name = "run_on_gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
emu_core = {version ="0.1.1"}
zerocopy = "0.6.1"
emu_glsl = "0.1.0"
futures = "0.3.21"
