[package]
name = "optimize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon ="1.5.2"
num_cpus = "1.0"
cached = "0.39.0"
