/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function decomp(n: number, multi: boolean): string
export function encodeRailFenceCipher(text: string, numRails: number): string
export function decodeRailFenceCipher(text: string, numRails: number): string
export function listSquared(m: number, n: number): Array<Array<number>>
export function crc32(st: string): number
export function crc3(st: string): number
export function longAddition(a: string, b: string): string
export function longAdd(a: string, b: string): string
export function toRoman(n: number): string
export function fromRoman(s: string): number
export function alphametics(input: string): string
