/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function encodeRailFenceCipher(text: string, numRails: number): string
export function decodeRailFenceCipher(text: string, numRails: number): string
export function listSquared(m: number, n: number): Array<Array<number>>
export function crc32(st: string): number
export function crc3(st: string): number
export function longAddition(right: string, left: string): string
